# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('is_doctor', models.CharField(max_length=128)),
                ('num_of_patients', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('patients', models.CharField(max_length=1024)),
                ('birthday_message', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=128)),
                ('message_path', models.CharField(max_length=128)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.DoctorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=128)),
                ('cell_phone', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.DoctorProfile')),
            ],
        ),
    ]
