# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20160505_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
